`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 06/08/2021 10:40:09 AM
// Design Name: 
// Module Name: conv224_64_blue
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module conv224_64_blue(
    result0,
    result1,
    result2,
    result3,
    result4,
    result5,
    result6,
    result7,
    result8,
    result9,
    result10,
    result11,
    result12,
    result13,
    result14,
    result15,
    result16,
    result17,
    result18,
    result19,
    result20,
    result21,
    result22,
    result23,
    result24,
    result25,
    result26,
    result27,
    result28,
    result29,
    result30,
    result31,
    result32,
    result33,
    result34,
    result35,
    result36,
    result37,
    result38,
    result39,
    result40,
    result41,
    result42,
    result43,
    result44,
    result45,
    result46,
    result47,
    result48,
    result49,
    result50,
    result51,
    result52,
    result53,
    result54,
    result55,
    result56,
    result57,
    result58,
    result59,
    result60,
    result61,
    result62,
    result63,
    counter,
    rowcounter,
    rst,
    clk,
    dataIn
    );
    
    input wire [31:0] dataIn;
    input wire clk, rst;
    output wire [31:0] result0,
                    result1,
                    result2,
                    result3,
                    result4,
                    result5,
                    result6,
                    result7,
                    result8,
                    result9,
                    result10,
                    result11,
                    result12,
                    result13,
                    result14,
                    result15,
                    result16,
                    result17,
                    result18,
                    result19,
                    result20,
                    result21,
                    result22,
                    result23,
                    result24,
                    result25,
                    result26,
                    result27,
                    result28,
                    result29,
                    result30,
                    result31,
                    result32,
                    result33,
                    result34,
                    result35,
                    result36,
                    result37,
                    result38,
                    result39,
                    result40,
                    result41,
                    result42,
                    result43,
                    result44,
                    result45,
                    result46,
                    result47,
                    result48,
                    result49,
                    result50,
                    result51,
                    result52,
                    result53,
                    result54,
                    result55,
                    result56,
                    result57,
                    result58,
                    result59,
                    result60,
                    result61,
                    result62,
                    result63;
    output wire [9:0] counter;
    output wire [7:0] rowcounter;
    
    wire [31:0] kernal0,
                    kernal1,
                    kernal2,
                    kernal3,
                    kernal4,
                    kernal5,
                    kernal6,
                    kernal7,
                    kernal8;
                   
lineBuffer_conv line0(
    .dataOut_0(kernal0),
    .dataOut_1(kernal1),
    .dataOut_2(kernal2),
    .dataOut_3(kernal3),
    .dataOut_4(kernal4),
    .dataOut_5(kernal5),
    .dataOut_6(kernal6),
    .dataOut_7(kernal7),
    .dataOut_8(kernal8),
    .counter(counter),
    .rowcounter(rowcounter),
    .clk(clk),
    .rst(rst),
    .dataIn(dataIn)
    );
    
filter_64_224_blue blue0(
    .result0(result0),
    .result1(result1),
    .result2(result2),
    .result3(result3),
    .result4(result4),
    .result5(result5),
    .result6(result6),
    .result7(result7),
    .result8(result8),
    .result9(result9),
    .result10(result10),
    .result11(result11),
    .result12(result12),
    .result13(result13),
    .result14(result14),
    .result15(result15),
    .result16(result16),
    .result17(result17),
    .result18(result18),
    .result19(result19),
    .result20(result20),
    .result21(result21),
    .result22(result22),
    .result23(result23),
    .result24(result24),
    .result25(result25),
    .result26(result26),
    .result27(result27),
    .result28(result28),
    .result29(result29),
    .result30(result30),
    .result31(result31),
    .result32(result32),
    .result33(result33),
    .result34(result34),
    .result35(result35),
    .result36(result36),
    .result37(result37),
    .result38(result38),
    .result39(result39),
    .result40(result40),
    .result41(result41),
    .result42(result42),
    .result43(result43),
    .result44(result44),
    .result45(result45),
    .result46(result46),
    .result47(result47),
    .result48(result48),
    .result49(result49),
    .result50(result50),
    .result51(result51),
    .result52(result52),
    .result53(result53),
    .result54(result54),
    .result55(result55),
    .result56(result56),
    .result57(result57),
    .result58(result58),
    .result59(result59),
    .result60(result60),
    .result61(result61),
    .result62(result62),
    .result63(result63),
    .in0(kernal0),
    .in1(kernal1),
    .in2(kernal2),
    .in3(kernal3),
    .in4(kernal4),
    .in5(kernal5),
    .in6(kernal6),
    .in7(kernal7),
    .in8(kernal8)
    );
    
endmodule
